name: Deploy to Heroku

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository and Heroku Login
        uses: actions/checkout@master
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:login 
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "weaponsforge-emailsender"
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web