name: Deploy to Heroku

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Heroku Login Credentials
        run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          EOF
      - name: Push to Heroku
        run: heroku git:remote -a $HEROKU_APP
        run: git push heroku HEAD:refs/heads/master